baseURL = "https://edsoncelio.github.io"
languageCode = "en-us"

title = "Edson Celio"
#title = "Welcome"
theme = "hyde-hyde" 

## Hugo Built-in Features
disqusShortname = "personal-blog-rktwn6gwzh"
googleAnalytics = "UA-155121170-1"
# enableRobotsTXT = true

summarylength = 20

paginate = 5

## Site Settings
[params]
    author = "Edson Celio - personal page"
    #title = "DevOps Guy"
    description = "Systems Analyst | Developer | DevOps Enthusiastic"
    authorimage = "/img/profile.png"
    dateformat = "Jan 2, 2006"
	
	# Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
    clearReading = true
  	
		
    # sidebar, copyright & license
    copyright = "tuxpilgrim"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"
    
    # Time to read
    noreadingtime = true

## Social Accounts
[params.social]
    github = "edsoncelio"
    linkedin = "edsoncelio"
    twitter = "tuxpilgrim"
    stackoverflow = "tuxpilgrim"
    #telegram = "<username>"
    email = "edsoncelio2020@gmail.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 150
    identifier = "posts"
    url = "/posts/"
#[[menu.main]]
#    name = "Posts(inglês)"
#    identifier = "posts-en"
#    weight = 150
#    url = "/posts-en/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 350
    url = "/about/"

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 20

anchor = "smart"
